# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: gh:oca/oca-addons-repo-template
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: ACSONE SA/NV
org_slug: acsone
rebel_module_groups: []
repo_description: 'Add Statecharts to Odoo models.


    There is no documentation yet. In the meantime here are the Odoo Experience 2018

    [slides](https://docs.google.com/presentation/d/e/2PACX-1vR9VGsSQUnITdnQq5KRiWnY7o-yERCB8YfnqxzhFW5tFcJ8AzMmIQ1CpLTdEgy5Sz9nx-yQlC0BhyGR/pub?start=false&loop=false&delayms=3000)
    and

    [video](https://www.youtube.com/watch?v=ssgl0kraOMc) which should get you started.'
repo_name: SCObidoo
repo_slug: scobidoo
repo_website: https://github.com/acsone/scobidoo
use_pyproject_toml: true
use_ruff: true

