sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

python:
  - "2.7"

before_install:
  - pip install acsoo
  - pip install codecov
  - DB_NAME=${TRAVIS_JOB_ID}
  - ADDONS_INST=$(acsoo addons list-depends)
  - ADDONS_TEST=$(acsoo addons list)
  - for addon in $(acsoo addons -s " " list); do echo "-e ./setup/$addon" >> requirements-test.txt; done

jobs:
  include:
    - stage: test
      env: FLAKE8=1
      script: 
        - echo "Flake8 check $ADDONS_TEST"
        - acsoo flake8
    - stage: test
      env: PYLINT=1
      script:
        - echo "Pylint check $ADDONS_TEST"
        - acsoo pylint
    - stage: test
      env: ODOO=1
      install:
        - pip install -r requirements-test.txt
      script:
        - echo "Installing $ADDONS_INST"
        - unbuffer ${VIRTUAL_ENV}/bin/odoo -d ${DB_NAME} --stop-after-init -i ${ADDONS_INST} | acsoo checklog
        - echo "Testing $ADDONS_TEST"
        - unbuffer coverage run ${VIRTUAL_ENV}/bin/odoo -d ${DB_NAME} --stop-after-init -i ${ADDONS_TEST} --test-enable | acsoo checklog
      after_success:
        - codecov
